ALTER SESSION SET CURRENT_SCHEMA = SOFKA;


CREATE TABLE TRANSACCIONES (
  ID_TRANSACCION NUMBER(19,0)
    GENERATED ALWAYS AS IDENTITY,
  MONTO NUMBER(15,2) NOT NULL,
  COMISION NUMBER(15,2) NOT NULL,
  DESCRIPCION VARCHAR2(300) NOT NULL,
  FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TRANSACCIONES PRIMARY KEY (ID_TRANSACCION)
);

commit